import json
from engine import analyze_phishing_target

# Test STATIC analysis (DEMO mode)
result = analyze_phishing_target('https://chase-security-login-portal.xyz/auth/verify', 'DEMO', [])
print('=== STATIC ANALYSIS (DEMO mode) ===')
print(f'Risk Score: {result["risk"]["score"]}')
print(f'Risk Level: {result["risk"]["level"]}')
print(f'DNS Score: {result["signals"]["dns"]}')
print(f'SSL Score: {result["signals"]["ssl"]}')
print(f'Redirect Score: {result["signals"]["redirects"]}')
print(f'DNS Status: {result["signalDetails"][5]["status"]}')
print(f'SSL Status: {result["signalDetails"][6]["status"]}')
print(f'Redirect Status: {result["signalDetails"][7]["status"]}')
print(f'Engine: {result["engineUsed"]}')
print(f'Mode: {result["analysisMeta"]["mode"]}')
print(f'Live Probes: {result["analysisMeta"]["liveProbesPerformed"]}')
print(f'Signals Computed: {result["analysisMeta"]["signalsComputed"]}')
print()

# Test LIVE analysis
result2 = analyze_phishing_target('https://github.com', 'LIVE', [])
print('=== LIVE ANALYSIS ===')
print(f'Risk Score: {result2["risk"]["score"]}')
print(f'Risk Level: {result2["risk"]["level"]}')
print(f'DNS Score: {result2["signals"]["dns"]}')
print(f'SSL Score: {result2["signals"]["ssl"]}')
print(f'Redirect Score: {result2["signals"]["redirects"]}')
print(f'DNS Status: {result2["signalDetails"][5]["status"]}')
print(f'SSL Status: {result2["signalDetails"][6]["status"]}')
print(f'Redirect Status: {result2["signalDetails"][7]["status"]}')
print(f'Engine: {result2["engineUsed"]}')
print(f'Mode: {result2["analysisMeta"]["mode"]}')
print(f'Live Probes: {result2["analysisMeta"]["liveProbesPerformed"]}')
print(f'Signals Computed: {result2["analysisMeta"]["signalsComputed"]}')
print()

# Test safe site STATIC
result3 = analyze_phishing_target('https://microsoft.com', 'DEMO', [])
print('=== SAFE SITE STATIC ANALYSIS ===')
print(f'Risk Score: {result3["risk"]["score"]}')
print(f'Risk Level: {result3["risk"]["level"]}')
print(f'Matched Brand: {result3["matchedBrand"]}')
print(f'Engine: {result3["engineUsed"]}')
print(f'Mode: {result3["analysisMeta"]["mode"]}')
print(f'Live Probes: {result3["analysisMeta"]["liveProbesPerformed"]}')
print(f'Signals Computed: {result3["analysisMeta"]["signalsComputed"]}')